# Generated by Django 4.2.3 on 2025-01-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutri', '0002_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='price',
        ),
        migrations.AddField(
            model_name='meal',
            name='calories',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
