# Generated by Django 4.2.3 on 2025-01-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutri', '0004_meal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='fats',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='ingredients',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meal',
            name='protein',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
