# Generated by Django 4.2.3 on 2025-01-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutri', '0005_meal_carbs_meal_fats_meal_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='carbs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fats',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
