# Generated by Django 4.2.3 on 2025-01-24 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Nutri', '0007_comment_discussion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discussion',
        ),
    ]
