# Generated by Django 4.2.3 on 2025-01-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutri', '0008_delete_discussion'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='fibre',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='meal',
            name='category',
            field=models.CharField(choices=[('Vegan', 'Vegan'), ('Vegetarian', 'Vegetarian'), ('Halal', 'Halal')], max_length=255),
        ),
    ]
