# Generated by Django 4.2.3 on 2025-01-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutri', '0009_meal_fibre_alter_meal_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='meal',
            name='category',
        ),
        migrations.AddField(
            model_name='meal',
            name='categories',
            field=models.ManyToManyField(related_name='meals', to='Nutri.category'),
        ),
    ]
