# Generated by Django 4.2.3 on 2025-01-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nutri', '0012_alter_profile_activity_level_alter_profile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='carbs',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='categories',
            field=models.ManyToManyField(blank=True, to='Nutri.category'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fats',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='fibre',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='meal',
            name='ingredients',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='meal',
            name='instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='meal',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='meal',
            name='protein',
            field=models.FloatField(default=0.0),
        ),
        migrations.DeleteModel(
            name='FavouriteMeal',
        ),
    ]
